export * from './notFoundPage/NotfoundPage';
export * from './mainNewsPage/MainNewsPage';
export * from './placesPage/PlacesPage';
export * from './searchFormPage/SearchFormPage';
export * from './placeFullInformationPage/placeFullInformationPage';
export * from './mainPage/MainPage';
export * from './allNewsPage/allNewsPage';
export * from './loginFormPage/LoginFormPage';
export * from './registerFormPage/RegisterFormPage';